sudo: false
dist: trusty
language: cpp

os:
  - linux

compiler:
  - gcc

git:
  depth: 1

env:
  global:
    - secure: "Zk3bAxnp4OHPMMZYOSoM2chuMZXomp7BFcT54/Ag6C8RCqtpqQ+E6yHRp861xdWSVo9uZ/uGmD1pwPiIUK8Vs80+OwhFVvtor2MGXyQKX1oFYBg0mo5Z3Xzy+OPa3e0YBbe6SSqdUzDE1hIa7OrU8GWciIMobWQS7XIBbWg3TFU="

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
    export CC=gcc-8 CXX=g++-8 ASC_VERSION=WotLK;
    fi

install:
  - mkdir ascemu_build
  - cd ascemu_build
  - cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=0

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - zlib1g-dev
    - libssl-dev
    - libpcre3-dev
    - libbz2-dev
    - libmysqlclient-dev
    - libmysql++-dev
    - gcc-8
    - g++-8
  coverity_scan:
    project:
      name: AscEmu/AscEmu
      description: MMORPG Framework
    notification_email: autokaori@gmail.com
    build_command_prepend: cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_WITH_WARNINGS=0 -DBUILD_TOOLS=0 -DASCEMU_VERSION=${ASC_VERSION} -DWITH_EXPERIMENTAL_FILESYSTEM=1 && cov-configure --comptype gcc --compiler gcc-8 --template
    build_command: make -j 4
    branch_pattern: coverity_scan

before_script:
  - ${CXX} --version
  - ${CC} --version
  - cmake --version

script:
  - make -j 4

#after_script:
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/build-log.txt
#  - echo "===================================================================================================="
#  - cat /home/travis/build/AscEmu/AscEmu/ascemu_build/cov-int/scm_log.txt